/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f7f9ff",
        "surface-variant": "#d1e4fb",
        "tertiary-fixed": "#cce5ff",
        "on-secondary-fixed-variant": "#713700",
        "on-error-container": "#93000a",
        "outline": "#6d7b6c",
        "tertiary-fixed-dim": "#92ccff",
        "surface-container": "#e3efff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#53e076",
        "surface": "#f7f9ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-background": "#091d2e",
        "primary": "#006e2d",
        "primary-fixed": "#72fe8f",
        "on-surface-variant": "#3d4a3d",
        "on-surface": "#091d2e",
        "on-primary-fixed-variant": "#005320",
        "primary-container": "#1db954",
        "on-primary-fixed": "#002108",
        "inverse-surface": "#203243",
        "secondary-fixed-dim": "#ffb783",
        "on-tertiary-fixed": "#001d31",
        "inverse-primary": "#53e076",
        "surface-container-low": "#edf4ff",
        "surface-container-high": "#d9eaff",
        "secondary-fixed": "#ffdcc5",
        "error-container": "#ffdad6",
        "secondary": "#944a00",
        "secondary-container": "#fc8f34",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#004b73",
        "inverse-on-surface": "#e8f2ff",
        "on-tertiary-container": "#003b5c",
        "surface-bright": "#f7f9ff",
        "on-primary-container": "#004118",
        "on-secondary": "#ffffff",
        "tertiary": "#006397",
        "surface-dim": "#c9dcf3",
        "tertiary-container": "#49a8ec",
        "surface-tint": "#006e2d",
        "outline-variant": "#bccbb9",
        "surface-container-highest": "#d1e4fb",
        "on-secondary-container": "#663100",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "4px",
        "lg": "24px",
        "margin-mobile": "20px",
        "gutter": "16px",
        "xs": "4px",
        "sm": "8px",
        "xl": "32px",
        "md": "16px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-bold": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
